name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_GH_TOKEN }}

          #PageSpeed (https://github.com/lowlighter/metrics/tree/master/source/plugins/pagespeed) 
          plugin_pagespeed: true
          plugin_pagespeed_url: https://www.phyrone.de/
          plugin_pagespeed_detailed: true
          plugin_pagespeed_pwa: false
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_API_KEY}}

          # Habits (https://github.com/lowlighter/metrics/tree/master/source/plugins/habits) 
          plugin_habits: true
          plugin_habits_facts: true
          plugin_habits_charts: true
          config_timezone: Europe/Berlin

          # Lines (https://github.com/lowlighter/metrics/tree/master/source/plugins/lines)
          plugin_lines: true
          
